version: "3.8"

services:
  e-commerce-client:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: e-commerce-client
    environment:
      - HOST_NAME=${HOST_NAME}
      - NEXT_PUBLIC_HOST_NAME=${NEXT_PUBLIC_HOST_NAME}
      - JWT_SECRET=${JWT_SECRET}
      - NODE_ENV=${NODE_ENV}
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - app-network

networks:
  app-network:
    driver: bridge