import type { Metadata } from "next";
import "./globals.css";
import { Merriweather } from "next/font/google";

import ReduxProvider from "./store-provider";
import Footer from "./components/Footer";
import Navbar from "./components/navbar/NavbarMain";

const merriweather = Merriweather({
  subsets: ["latin"],
  weight: ["400", "700"],
  style: "normal",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  auth,
}: Readonly<{
  children: React.ReactNode;
  auth: React.ReactNode;
}>) {
  return (
    <ReduxProvider>
      <html lang="en">
        <body className={`${merriweather.className} antialiased`}>
          <Navbar />
          {auth}
          {children}
          <Footer />
        </body>
      </html>
    </ReduxProvider>
  );
}
