import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./components/Navbar";
import ReduxProvider from "./store-provider";

import { Merriweather } from "next/font/google";
import { decryptToken, getToken } from "./utils/token";

const merriweather = Merriweather({
  subsets: ["latin"],
  weight: ["400", "700"],
  style: "normal",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const userToken = await getToken();

  const userInfo = userToken ? await decryptToken(userToken) : null;

  return (
    <ReduxProvider>
      <html lang="en">
        <body className={`${merriweather.className} antialiased`}>
          {/* ส่งข้อมูล userInfo ไปที่ Navbar */}
          <Navbar userInfo={userInfo} />
          {children}
        </body>
      </html>
    </ReduxProvider>
  );
}
